//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public int MaGiamGiaID { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> SoTienGiam { get; set; }
        public Nullable<bool> LaPhanTram { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> SoLuongConLai { get; set; }
    }
}
