//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.AnhSanPhams = new HashSet<AnhSanPham>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhSachYeuThiches = new HashSet<DanhSachYeuThich>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string SKU { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaChiTiet { get; set; }
        public decimal GiaGoc { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string HinhAnhChinh { get; set; }
        public Nullable<bool> LaHangMoi { get; set; }
        public Nullable<bool> LaBanChay { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhSanPham> AnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThiches { get; set; }
    }
}
